// Code generated by go-dds-idlgen. DO NOT EDIT.

package interop

import (
	"github.com/shirou/go-dds-idlgen/cdr"
)

// Ensure cdr import is used.
var _ = cdr.LittleEndian

// Color represents the IDL enum Color.
type Color int32

const (
	ColorRED   Color = 0
	ColorGREEN Color = 1
	ColorBLUE  Color = 2
)

func (e *Color) EncodeCDR(enc *cdr.Encoder) error {
	return enc.WriteInt32(int32(*e))
}

func (e *Color) DecodeCDR(dec *cdr.Decoder) error {
	v, err := dec.ReadInt32()
	if err != nil {
		return err
	}
	*e = Color(v)
	return nil
}

// Point represents the IDL struct Point.
type Point struct {
	X float64
	Y float64
	Z float64
}

// PrimitiveTypes represents the IDL struct PrimitiveTypes.
type PrimitiveTypes struct {
	ValBool      bool
	ValOctet     uint8
	ValShort     int16
	ValUshort    uint16
	ValLong      int32
	ValUlong     uint32
	ValLonglong  int64
	ValUlonglong uint64
	ValFloat     float32
	ValDouble    float64
	ValString    string
}

// KeyedMessage represents the IDL struct KeyedMessage.
type KeyedMessage struct {
	ID          int32
	Topic       string
	Payload     string
	TimestampNs int64
}

// WithSequence represents the IDL struct WithSequence.
type WithSequence struct {
	Count  int32
	Values []int32
	Label  string
}

// WithEnum represents the IDL struct WithEnum.
type WithEnum struct {
	ID          int32
	Color       Color
	Description string
}

// CDRExtensibility returns the extensibility kind of Point.
func (s *Point) CDRExtensibility() cdr.ExtensibilityKind {
	return cdr.FINAL
}

// MarshalCDR serializes Point into CDR format with encapsulation header.
func (s *Point) MarshalCDR() ([]byte, error) {
	enc := cdr.NewEncoder(cdr.GetEncapsulationKind(s.CDRExtensibility()))
	if err := s.EncodeCDR(enc); err != nil {
		return nil, err
	}
	return enc.Bytes(), nil
}

// UnmarshalCDR deserializes Point from CDR format, reading the encapsulation header.
func (s *Point) UnmarshalCDR(data []byte) error {
	dec, err := cdr.NewDecoder(data)
	if err != nil {
		return err
	}
	return s.DecodeCDR(dec)
}

// EncodeCDR serializes Point using XCDR2 FINAL encoding.
func (s *Point) EncodeCDR(enc *cdr.Encoder) error {
	if err := enc.WriteFloat64(s.X); err != nil {
		return err
	}
	if err := enc.WriteFloat64(s.Y); err != nil {
		return err
	}
	if err := enc.WriteFloat64(s.Z); err != nil {
		return err
	}
	return nil
}

// DecodeCDR deserializes Point using XCDR2 FINAL encoding.
func (s *Point) DecodeCDR(dec *cdr.Decoder) error {
	{
		v, err := dec.ReadFloat64()
		if err != nil {
			return err
		}
		s.X = v
	}
	{
		v, err := dec.ReadFloat64()
		if err != nil {
			return err
		}
		s.Y = v
	}
	{
		v, err := dec.ReadFloat64()
		if err != nil {
			return err
		}
		s.Z = v
	}
	return nil
}

// CDRExtensibility returns the extensibility kind of PrimitiveTypes.
func (s *PrimitiveTypes) CDRExtensibility() cdr.ExtensibilityKind {
	return cdr.FINAL
}

// MarshalCDR serializes PrimitiveTypes into CDR format with encapsulation header.
func (s *PrimitiveTypes) MarshalCDR() ([]byte, error) {
	enc := cdr.NewEncoder(cdr.GetEncapsulationKind(s.CDRExtensibility()))
	if err := s.EncodeCDR(enc); err != nil {
		return nil, err
	}
	return enc.Bytes(), nil
}

// UnmarshalCDR deserializes PrimitiveTypes from CDR format, reading the encapsulation header.
func (s *PrimitiveTypes) UnmarshalCDR(data []byte) error {
	dec, err := cdr.NewDecoder(data)
	if err != nil {
		return err
	}
	return s.DecodeCDR(dec)
}

// EncodeCDR serializes PrimitiveTypes using XCDR2 FINAL encoding.
func (s *PrimitiveTypes) EncodeCDR(enc *cdr.Encoder) error {
	if err := enc.WriteBool(s.ValBool); err != nil {
		return err
	}
	if err := enc.WriteUint8(s.ValOctet); err != nil {
		return err
	}
	if err := enc.WriteInt16(s.ValShort); err != nil {
		return err
	}
	if err := enc.WriteUint16(s.ValUshort); err != nil {
		return err
	}
	if err := enc.WriteInt32(s.ValLong); err != nil {
		return err
	}
	if err := enc.WriteUint32(s.ValUlong); err != nil {
		return err
	}
	if err := enc.WriteInt64(s.ValLonglong); err != nil {
		return err
	}
	if err := enc.WriteUint64(s.ValUlonglong); err != nil {
		return err
	}
	if err := enc.WriteFloat32(s.ValFloat); err != nil {
		return err
	}
	if err := enc.WriteFloat64(s.ValDouble); err != nil {
		return err
	}
	if err := enc.WriteString(s.ValString); err != nil {
		return err
	}
	return nil
}

// DecodeCDR deserializes PrimitiveTypes using XCDR2 FINAL encoding.
func (s *PrimitiveTypes) DecodeCDR(dec *cdr.Decoder) error {
	{
		v, err := dec.ReadBool()
		if err != nil {
			return err
		}
		s.ValBool = v
	}
	{
		v, err := dec.ReadUint8()
		if err != nil {
			return err
		}
		s.ValOctet = v
	}
	{
		v, err := dec.ReadInt16()
		if err != nil {
			return err
		}
		s.ValShort = v
	}
	{
		v, err := dec.ReadUint16()
		if err != nil {
			return err
		}
		s.ValUshort = v
	}
	{
		v, err := dec.ReadInt32()
		if err != nil {
			return err
		}
		s.ValLong = v
	}
	{
		v, err := dec.ReadUint32()
		if err != nil {
			return err
		}
		s.ValUlong = v
	}
	{
		v, err := dec.ReadInt64()
		if err != nil {
			return err
		}
		s.ValLonglong = v
	}
	{
		v, err := dec.ReadUint64()
		if err != nil {
			return err
		}
		s.ValUlonglong = v
	}
	{
		v, err := dec.ReadFloat32()
		if err != nil {
			return err
		}
		s.ValFloat = v
	}
	{
		v, err := dec.ReadFloat64()
		if err != nil {
			return err
		}
		s.ValDouble = v
	}
	{
		v, err := dec.ReadString()
		if err != nil {
			return err
		}
		s.ValString = v
	}
	return nil
}

// CDRExtensibility returns the extensibility kind of KeyedMessage.
func (s *KeyedMessage) CDRExtensibility() cdr.ExtensibilityKind {
	return cdr.FINAL
}

// MarshalCDR serializes KeyedMessage into CDR format with encapsulation header.
func (s *KeyedMessage) MarshalCDR() ([]byte, error) {
	enc := cdr.NewEncoder(cdr.GetEncapsulationKind(s.CDRExtensibility()))
	if err := s.EncodeCDR(enc); err != nil {
		return nil, err
	}
	return enc.Bytes(), nil
}

// UnmarshalCDR deserializes KeyedMessage from CDR format, reading the encapsulation header.
func (s *KeyedMessage) UnmarshalCDR(data []byte) error {
	dec, err := cdr.NewDecoder(data)
	if err != nil {
		return err
	}
	return s.DecodeCDR(dec)
}

// EncodeCDR serializes KeyedMessage using XCDR2 FINAL encoding.
func (s *KeyedMessage) EncodeCDR(enc *cdr.Encoder) error {
	if err := enc.WriteInt32(s.ID); err != nil {
		return err
	}
	if err := enc.WriteString(s.Topic); err != nil {
		return err
	}
	if err := enc.WriteString(s.Payload); err != nil {
		return err
	}
	if err := enc.WriteInt64(s.TimestampNs); err != nil {
		return err
	}
	return nil
}

// DecodeCDR deserializes KeyedMessage using XCDR2 FINAL encoding.
func (s *KeyedMessage) DecodeCDR(dec *cdr.Decoder) error {
	{
		v, err := dec.ReadInt32()
		if err != nil {
			return err
		}
		s.ID = v
	}
	{
		v, err := dec.ReadString()
		if err != nil {
			return err
		}
		s.Topic = v
	}
	{
		v, err := dec.ReadString()
		if err != nil {
			return err
		}
		s.Payload = v
	}
	{
		v, err := dec.ReadInt64()
		if err != nil {
			return err
		}
		s.TimestampNs = v
	}
	return nil
}

// CDRExtensibility returns the extensibility kind of WithSequence.
func (s *WithSequence) CDRExtensibility() cdr.ExtensibilityKind {
	return cdr.FINAL
}

// MarshalCDR serializes WithSequence into CDR format with encapsulation header.
func (s *WithSequence) MarshalCDR() ([]byte, error) {
	enc := cdr.NewEncoder(cdr.GetEncapsulationKind(s.CDRExtensibility()))
	if err := s.EncodeCDR(enc); err != nil {
		return nil, err
	}
	return enc.Bytes(), nil
}

// UnmarshalCDR deserializes WithSequence from CDR format, reading the encapsulation header.
func (s *WithSequence) UnmarshalCDR(data []byte) error {
	dec, err := cdr.NewDecoder(data)
	if err != nil {
		return err
	}
	return s.DecodeCDR(dec)
}

// EncodeCDR serializes WithSequence using XCDR2 FINAL encoding.
func (s *WithSequence) EncodeCDR(enc *cdr.Encoder) error {
	if err := enc.WriteInt32(s.Count); err != nil {
		return err
	}
	if err := enc.WriteUint32(uint32(len(s.Values))); err != nil {
		return err
	}
	for _, elem := range s.Values {
		if err := enc.WriteInt32(elem); err != nil {
			return err
		}
	}
	if err := enc.WriteString(s.Label); err != nil {
		return err
	}
	return nil
}

// DecodeCDR deserializes WithSequence using XCDR2 FINAL encoding.
func (s *WithSequence) DecodeCDR(dec *cdr.Decoder) error {
	{
		v, err := dec.ReadInt32()
		if err != nil {
			return err
		}
		s.Count = v
	}
	{
		n, err := dec.ReadUint32()
		if err != nil {
			return err
		}
		s.Values = make([]int32, n)
		for i := uint32(0); i < n; i++ {
			v, err := dec.ReadInt32()
			if err != nil {
				return err
			}
			s.Values[i] = v
		}
	}
	{
		v, err := dec.ReadString()
		if err != nil {
			return err
		}
		s.Label = v
	}
	return nil
}

// CDRExtensibility returns the extensibility kind of WithEnum.
func (s *WithEnum) CDRExtensibility() cdr.ExtensibilityKind {
	return cdr.FINAL
}

// MarshalCDR serializes WithEnum into CDR format with encapsulation header.
func (s *WithEnum) MarshalCDR() ([]byte, error) {
	enc := cdr.NewEncoder(cdr.GetEncapsulationKind(s.CDRExtensibility()))
	if err := s.EncodeCDR(enc); err != nil {
		return nil, err
	}
	return enc.Bytes(), nil
}

// UnmarshalCDR deserializes WithEnum from CDR format, reading the encapsulation header.
func (s *WithEnum) UnmarshalCDR(data []byte) error {
	dec, err := cdr.NewDecoder(data)
	if err != nil {
		return err
	}
	return s.DecodeCDR(dec)
}

// EncodeCDR serializes WithEnum using XCDR2 FINAL encoding.
func (s *WithEnum) EncodeCDR(enc *cdr.Encoder) error {
	if err := enc.WriteInt32(s.ID); err != nil {
		return err
	}
	if err := s.Color.EncodeCDR(enc); err != nil {
		return err
	}
	if err := enc.WriteString(s.Description); err != nil {
		return err
	}
	return nil
}

// DecodeCDR deserializes WithEnum using XCDR2 FINAL encoding.
func (s *WithEnum) DecodeCDR(dec *cdr.Decoder) error {
	{
		v, err := dec.ReadInt32()
		if err != nil {
			return err
		}
		s.ID = v
	}
	if err := s.Color.DecodeCDR(dec); err != nil {
		return err
	}
	{
		v, err := dec.ReadString()
		if err != nil {
			return err
		}
		s.Description = v
	}
	return nil
}
